apiVersion: v1
kind: Service
metadata:
  name: anlalytics-api
spec:
  selector:
    app.kubernetes.io/name: anlalytics-api
  ports:
    - name: '5153'
      protocol: TCP
      port: 5153
      targetPort: 5153
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anlalytics-api
  labels:
    name: anlalytics-api
spec:
  replicas: 1
  selector:
    matchLabels:
      service: anlalytics-api
  template:
    metadata:
      labels:
        service: anlalytics-api
    spec:
      containers:
        - name: anlalytics-api
          image: 689357237475.dkr.ecr.us-east-1.amazonaws.com/analytics-api:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /health_check
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: '/readiness_check'
              port: 5153
            initialDelaySeconds: 5
            timeoutSeconds: 5
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: app-db
      restartPolicy: Always
